spring:
  profiles:
    active: local

  mail:
    host: smtp.gmail.com
    port: 587
    username: ku.rum.authentication@gmail.com
    password: eofxovqewkdkhuek
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 1000
          starttls:
            enable: true
openai:
  model: gpt-3.5-turbo
  api:
    key: temp
    url: temp

secret:
  jwt-secret-key: 6ce1d11af9ac1adf97712c069ca33bc4564d675ce3958942bb3dc5601829881430cfd8d98c87452ae5b098d80874df8ca569c03fa79191b4ae755e86fd719347
  accessToken-valid-time: 1800000
  refreshToken-valid-time: 604800000

---
spring:
  config:
    activate:
      on-profile : dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9000

logging:
  level:
    org.springframework.cache : trace
#    root: debug

---
spring:
  config:
    activate:
      on-profile : local

  datasource:
    url: jdbc:h2:mem:~/BackendApplication;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true


  data:
    redis:
      port: 6379
      host: localhost

server:
  port: 8080