# 로컬, 개발 환경 appliction.yml 파일 통합
spring:
  application:
    name: kurum
  profiles:
    group:
      local: port-local
      dev: port-prod
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  # H2 데이터 베이스
  datasource:
    url: jdbc:h2:mem:~/BackendApplication;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # ddl 전략 update
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true

  data:
    redis:
      port: 6379
      host: localhost
---
# 배포 환경
spring:
  config:
    activate:
      on-profile: prod

  # ddl 전략 none
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: none
    show-sql: true

  # 외부 데이터 베이스
  datasource:
    url: ${DB.URL}
    username: ${DB.USERNAME}
    password: ${DB.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 레디스
  data:
    redis:
      host: localhost
      port: 6379

# 로깅 전략
logging:
  level:
    org.springframework.cache: trace
---
#로컬 포트
spring:
  config:
    activate:
      on-profile: port-local

server:
  port: 9000
---
# 배포용 포트
spring:
  config:
    activate:
      on-profile: port-prod

server:
  port: 8080
---
# 공통
spring:
  # 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 1000
          starttls:
            enable: true
# 챗봇 설정
openai:
  model: gpt-3.5-turbo
  api:
    key: ${openai.key}
    url: ${openai.key}

# JWT 설정
secret:
  jwt-secret-key: ${jwt-secret-key}
  accessToken-valid-time: 1800000 # 1시간
  refreshToken-valid-time: 604800000 # 일주일